service: nuxt-lambda-ashnamuh2

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-2

functions:
  render:
    warmup:
      enabled: true
    handler: server/handler.render
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - pages/**
    - components/**
    - store/**
    - static/**
    - assets/**
    - layouts/**
    - plugins/**
    - test/**
    - middleware/**
    - README.md
    - package.json
    - package-lock.json
    - node_modules/**/*.md
    - node_modules/**/bin/**
  include:
    - server/**
    - config/**
    - nuxt.config.js
    - .nuxt/**
    - node_modules/autoprefixer/**
    - node_modules/babel-runtime/**
    - node_modules/babel-extract-comments/**

plugins:
  - serverless-apigw-binary
  - serverless-plugin-warmup

custom:
  apigwBinary:
    types:
      - '*/*'
